application: devnook-devrel
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

- url: /(.*\.xml)
  mime_type: application/xml
  static_files: static/\1
  upload: static/(.*\.xml)

- url: /samples/(.*\.html)
  mime_type: text/html
  static_files: samples/\1
  upload: samples/(.*\.html)

- url: /images
  static_dir: images

- url: /css
  static_dir: css

- url: /js
  static_dir: js

- url: /success
  script: main.app

- url: /failure
  script: main.app

- url: .*
  script: main.app
  login: required

libraries:
- name: webapp2
  version: "2.5.2"
- name: jinja2
  version: latest
